<?php
include "db.php";

if (function_exists($_GET['function'])) {
    $_GET['function']();
}

function post_header()
{
    global $db;
    $insert = '"' . $_GET['DATA'] . '"';
    $insert2 = str_replace("%20", " ", $insert);
    // $insert = $_GET['DATA'];
    // $update = $db->query("INSERT INTO plb_header (NOMOR_AJU, KPPBC, PERUSAHAAN, PEMASOK, STATUS, KODE_DOKUMEN_PABEAN, NPPJK, ALAMAT_PEMASOK, ALAMAT_PEMILIK, ALAMAT_PENERIMA_BARANG, ALAMAT_PENGIRIM, ALAMAT_PENGUSAHA, ALAMAT_PPJK, API_PEMILIK, API_PENERIMA, API_PENGUSAHA, ASAL_DATA, ASURANSI, BIAYA_TAMBAHAN, BRUTO, CIF, CIF_RUPIAH, DISKON, FLAG_PEMILIK, URL_DOKUMEN_PABEAN, FOB, FREIGHT, HARGA_BARANG_LDP, HARGA_INVOICE, HARGA_PENYERAHAN, HARGA_TOTAL, ID_MODUL, ID_PEMASOK, ID_PEMILIK, ID_PENERIMA_BARANG, ID_PENGIRIM, ID_PENGUSAHA, ID_PPJK, JABATAN_TTD, JUMLAH_BARANG, JUMLAH_KEMASAN, JUMLAH_KONTAINER, KESESUAIAN_DOKUMEN, KETERANGAN, KODE_ASAL_BARANG, KODE_ASURANSI, KODE_BENDERA, KODE_CARA_ANGKUT, KODE_CARA_BAYAR, KODE_DAERAH_ASAL, KODE_FASILITAS, KODE_FTZ, KODE_HARGA, KODE_ID_PEMASOK, KODE_ID_PEMILIK, KODE_ID_PENERIMA_BARANG, KODE_ID_PENGIRIM, KODE_ID_PENGUSAHA, KODE_ID_PPJK, KODE_JENIS_API, KODE_JENIS_API_PEMILIK, KODE_JENIS_API_PENERIMA, KODE_JENIS_API_PENGUSAHA, KODE_JENIS_BARANG, KODE_JENIS_BC25, KODE_JENIS_NILAI, KODE_JENIS_PEMASUKAN01, KODE_JENIS_PEMASUKAN_02, KODE_JENIS_TPB, KODE_KANTOR_BONGKAR, KODE_KANTOR_TUJUAN, KODE_LOKASI_BAYAR, KODE_NEGARA_PEMASOK, KODE_NEGARA_PENGIRIM, KODE_NEGARA_PEMILIK, KODE_NEGARA_TUJUAN, KODE_PEL_BONGKAR, KODE_PEL_MUAT, KODE_PEL_TRANSIT, KODE_PEMBAYAR, KODE_STATUS_PENGUSAHA, STATUS_PERBAIKAN, KODE_TPS, KODE_TUJUAN_PEMASUKAN, KODE_TUJUAN_PENGIRIMAN, KODE_TUJUAN_TPB, KODE_TUTUP_PU, KODE_VALUTA, KOTA_TTD, NAMA_PEMILIK, NAMA_PENERIMA_BARANG, NAMA_PENGANGKUT, NAMA_PENGIRIM, NAMA_PPJK, NAMA_TTD, NDPBM, NETTO, NILAI_INCOTERM, NIPER_PENERIMA, NOMOR_API, NOMOR_BC11, NOMOR_BILLING, NOMOR_DAFTAR, NOMOR_IJIN_BPK_PEMASOK, NOMOR_IJIN_BPK_PENGUSAHA, NOMOR_IJIN_TPB, NOMOR_IJIN_TPB_PENERIMA, NOMOR_VOYV_FLIGHT, NPWP_BILLING, POS_BC11, SERI, SUBPOS_BC11, SUB_SUBPOS_BC11, TANGGAL_BC11, TANGGAL_BERANGKAT, TANGGAL_BILLING, TANGGAL_DAFTAR, TANGGAL_IJIN_BPK_PEMASOK, TANGGAL_IJIN_BPK_PENGUSAHA, TANGGAL_IJIN_TPB, TANGGAL_NPPPJK, TANGGAL_TIBA, TANGGAL_TTD, TANGGAL_JATUH_TEMPO, TOTAL_BAYAR, TOTAL_BEBAS, TOTAL_DILUNASI, TOTAL_JAMIN, TOTAL_SUDAH_DILUNASI, TOTAL_TANGGUH, TOTAL_TANGGUNG, TOTAL_TIDAK_DIPUNGUT, URL_DOKUMEN_PABEAN_2, VERSI_MODUL, VOLUME, WAKTU_BONGKAR, WAKTU_STUFFING, NOMOR_POLISI, CALL_SIGN, JUMLAH_TANDA_PENGAMAN, KODE_JENIS_TANDA_PENGAMAN, KODE_KANTOR_MUAT, KODE_PEL_TUJUAN, TANGGAL_STUFFING, TANGGAL_MUAT, KODE_GUDANG_ASAL, KODE_GUDANG_TUJUAN) VALUES ('16022701384620221005000110','160200','SARINAH (PERSERO)','','00','27','','','','MENARA BATAVIA LT.10-11 JL KH MAS MANSYUR KAV.126 KEL. KARET TENGSIN KEC.TANAH ABANG JAKARTA PUSAT','','DI GUDANG BERIKAT PT BHANDA GHARA REKSA, JALAN BOULEVARD, KOMPLEK PERGUDANGAN PT BGR BLOK J1, KELAPA GADING, JAKARTA UTARA','','','','','','','','14513.0000','313571.01','','','','','','','','','4442674069.68','','13846','','','013372248415001','','010000610051000','','DIREKTUR TRADING & PROPERTY','64','1','1','','','','','','','','','','','','','','1','','1','','','','','','','','','','','2','','050100','','','','','','','','','','','','','','1','4','','USD','JAKARTA','','PT DEWATAAGUNG WIBAWA','TRUCK BOX','','','RAKESH KUMAR ASHOK ADWANI','','7397.1000','','','','','','','','','287/KM.4/WBC.08/2020','1469/KPU.03/2019','','','','','','','','','','','','','','','','05 Oct 2022','','0.00','1208132000.00','0.00','','','','0.00','','','3.1.11','0.0000','','','B','','','','','','','','','') ");
    $update = $db->query($insert2);
    // echo $insert;

    if ($update) {
        echo 200;
    } else {
        echo 300;
    }
}